---
abstract: 'embedded SQL for perl'
author:
  - 'Kazuho Oku'
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Filter-SQL
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  DBI: 0
  Filter::Simple: 0.82
  List::MoreUtils: 0.21
  Text::Balanced: 2.0.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
