--- 
abstract: embedded SQL for perl
author: 
  - Kazuho Oku
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Filter-SQL
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBI: 0
  Filter::Simple: 0.82
version: 0.01
